### PR TITLE
 Allow run() to be executed multiple times 

### PR DESCRIPTION
**Pull request by merijnvdk**
The current code expects the run() to be called only once. This is
fine if you start the scheduler from cron each minute and re-initialize
it each time. If you want to manually run the scheduler, or maybe
have a lot of jobs you do not want to init each minute, it would
be useful to call run() multiple times in the lifetime of the
scheduler.

In this case the collected data of the last run should be reset.
the executedJobs, failedJobs and outputSchedule.

If the scheduler is used to do multiple runs then it would be useful
to reset all queued Jobs. Currently the only way to do this is by
re-creating the scheduler object. But if the object is injected in the
code then this is not practical.

### CODE REVIEW

**Comment by merijnvdk** [comment]
The PHP 7.1 Travis build seems to fail randomly 2-3 tests. The tests seem to be related to async_job.php and a test involving a sleep. My local PHP 7.1 test ran just fine:
OK (75 tests, 196 assertions)
So maybe this is some kind of timing issue? I think it is unrelated to my changes in this PR. The same for the other open PR I think.

**Comment by peppeocchi** [comment]
Hi @merijnvdk thank you for your PR, I know about the issue with travis-ci (it happened with another PR, not sure why though, in my local those tests are running just fine).

Can you please provide a use case for this PR?

Just as a reminder, the scheduler is meant to run as a cronjob, jobs should be executed only if due to run on that particular timeframe.
That being said, I can see the value on having the scheduler to do a fresh `run` more than one time.

Maybe there should be another function to manually trigger a fresh run?

To give you an example
```php
$scheduler->php('myscript.php');

$scheduler->run(); // myscript.php runs, the scheduler executed 1 job
// ...
$scheduler->php('my_other_script.php');
// ...
// both myscript.php and my_other_script.php are running now,
// the scheduler executed a total of 3 jobs since it started
$scheduler->run();
```

A different implementation of your PR could be
```php
$scheduler->php('myscript.php');

$scheduler->run(); // myscript.php runs, the scheduler executed 1 job
$scheduler->run(); // myscript.php runs again, the scheduler executed a total of 2 jobs
// here you are actively saying you want a fresh run
// inside this function you can reset the arrays
$scheduler->freshRun();
```

Another possible implementation could be
```php
$scheduler->php('myscript.php');
$scheduler->run();

// Actively reset the scheduler
// this will clear the queued jobs and everything else
$scheduler->reset();

$scheduler->php('my_other_script.php');
// In this case there is no need to have a "freshRun" method
$scheduler->run();
```

I think the correct implementation depends on a real use case.

Another possible implementation would be to have multiple scheduler instances.
In this case you are not losing scheduler reports during the execution of your script, while if you reset the scheduler you need to make sure to save any report you need.
```php
$easyJobs = [
    'myscript.php',
    ....
];
$heavyJobs = [
    'my_other_script.php',
    ....
];

$config = [...];

$schedulerEasyJobs = new Scheduler($config);
$schedulerHeavyJobs = new Scheduler($config);
foreach ($easyJobs as $job) {
    $schedulerEasyJobs->php($job);
}
$schedulerEasyJobs->run();

// ...

foreach ($heavyJobs as $job) {
    $schedulerHeavyJobs->php($job);
}
$schedulerHeavyJobs->run();

// ... at the end of your script you can call your log function

logSchedulerReports([$schedulerEasyJobs, $schedulerHeavyJobs]);
```

Again, a real use case would help choose the correct implementation for this feature.

**Comment by merijnvdk** [comment]
While I think most people would handle the results for each run, the freshRun() solution would at least be fully backwards compatible and the most flexible solution. But it is a bit counter intuitive that run() returns a cummulative result instead of the executed jobs for that particular run.

I would not add a full reset() method because clearing the jobs and clearing the run() result are two different things. But a resetRun() would be ok too.

My use case is running the scheduler every minute from a daemon. And only re-adding all jobs (from external source) when they have changed (in that external source). So the scheduler has a long lifetime.

**Comment by peppeocchi** [comment]
@merijnvdk thank you, I am happy with merging these changes, can I ask you to send this PR to the [v2.x brach](https://github.com/peppeocchi/php-cron-scheduler/tree/v2.x) please?

**Comment by merijnvdk** [comment]
I think I managed to change it to the 2.1 branch, is it correct like this?

**Pull request merged**
